### ISSUE TITLE
say and command crash the game

### ISSUE THREAD

**Issue by dvirov** [ClockwerkKaiser/MineMenu-Refabricated#5]
when trying to set mesage with say option or command with the command option  or opisate the game crash 
[crash-2022-09-28_10.59.15-client.txt](https://github.com/ClockwerkKaiser/MineMenu-Refabricated/files/9662787/crash-2022-09-28_10.59.15-client.txt)

**Comment by ClockwerkKaiser** [comment]
1.19.2 isn't compatible yet. 

I plan on updating it soon. Can't give an ETA though.

**Comment by ClockwerkKaiser** [comment]
I just figured it out, I'll push the fixed update by tomorrow.
